experiment_name: "baseline_autogluon"

data:
  data_path: "data/data.parquet"
  target_col: "trip_per_user"
  timestamp_col: "timestamp"
  item_id_col: "item_id"

split:
  test_size: 0.1
  random_state: 42

autogluon:
  presets: "high_quality"
  time_limit: 300
  prediction_length: 10
  plot_history_days: 30

mlflow:
  tracking_uri: "sqlite:///data/mlflow.db"
