experiment_name: "baseline_autogluon"

data:
  data_path: "data/data.parquet"
  target_col: "trip_per_user"
  timestamp_col: "trip_date"
  item_id_col: "item_id"
  known_covariates_names: ["user_count"]

split:
  test_size: 0.2
  random_state: 42

autogluon:
  presets: "fast_training"
  time_limit: 30
  prediction_length: 10

mlflow:
  tracking_uri: "sqlite:///data/mlflow.db"
